services:
  postgres:
    image: postgres:15-alpine
    container_name: logistics-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-logistics_tracking}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-logistics_tracking}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - logistics-network

volumes:
  postgres_data:
    driver: local

networks:
  logistics-network:
    driver: bridge 